name: angelikasteiger
favicon: null
layout_spectrum: 0.5344732974190265
typography_spectrum: 0.6211437226738781
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2315971371717751
  lightness: 0.882797671481967
  saturation: 0.41856379248201847
  rhythmicContrast: 0.38441726425662637
purpose: []
