name: angelikasteiger
favicon: null
layout_spectrum: 0.86714
typography_spectrum: 0.15798
title: Angelika Steiger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b090c'
    - '#797067'
    - '#a2aa9f'
    - '#ffdc25'
    - '#d5824b'
  brandStrength: 0.0625
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
