name: angelikasteiger
favicon: null
layout_spectrum: 0.86714
typography_spectrum: 0.15798
title: Angelika Steiger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0b10'
    - '#f99c8a'
    - '#928268'
    - '#6d4a34'
  brandStrength: 0.5
  lightness: 0.882797671481967
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
