name: angelikasteiger
favicon: null
layout_spectrum: 0.65568
typography_spectrum: 0.15798
title: Angelika Steiger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6c60f2'
    - '#aaaaaa'
    - '#281fae'
    - '#4b4642'
  brandStrength: 0.125
  lightness: 0.882797671481967
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
